In [1]:
from datetime import datetime
import time
import json

import hashlib
import cv2

from SessionClass import Session

In [2]:
session = Session(
    video_path='test.mp4',
    model='model.pt',
    route_id="304A",
    bus_id="081433"
)

In [3]:
cnt = 0
while True:
    cnt += 1
    img = session.read_video()
    if img is None:
        break

    results = session.model(img, stream = True)
    cv2.imshow("Img", img)
    k = cv2.waitKey(1)
    if k == ord("q"):break

#     if cnt >= 400: #250
#         break
#     if results:
#         break
cv2.destroyAllWindows()

In [4]:
cv2.imshow("Img", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
cnt

1632

In [6]:
lst = []
for r in results:
    lst.append(r)
len(lst)


0: 640x640 2 Passengers, 64.8ms
Speed: 5.0ms preprocess, 64.8ms inference, 13.8ms postprocess per image at shape (1, 3, 640, 640)


1

In [7]:
lst[0]

ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: None
names: {0: 'Passenger'}
orig_img: array([[[88, 72, 62],
        [88, 72, 62],
        [88, 72, 62],
        ...,
        [31, 25, 20],
        [35, 29, 24],
        [28, 23, 17]],

       [[88, 72, 62],
        [88, 72, 62],
        [88, 72, 62],
        ...,
        [29, 23, 18],
        [32, 26, 21],
        [29, 23, 18]],

       [[88, 72, 62],
        [88, 72, 62],
        [88, 72, 62],
        ...,
        [36, 30, 25],
        [17, 11,  6],
        [49, 43, 38]],

       ...,

       [[20, 10, 12],
        [13,  3,  5],
        [20, 10, 12],
        ...,
        [45, 30, 17],
        [56, 41, 28],
        [54, 39, 26]],

       [[19,  9, 11],
        [19,  9, 11],
        [21, 11, 13],
        ...,
        [46, 31, 18],
        [55, 40, 27],
        [52, 37, 24]],

       [[56, 46, 48],
        [31, 21, 23],
        [27, 17, 19],
        ...,
    

In [8]:
boxes = lst[0].boxes
boxes

WARNING  'Boxes.boxes' is deprecated. Use 'Boxes.data' instead.


ultralytics.engine.results.Boxes object with attributes:

boxes: tensor([[ 31.0373,  44.5269, 220.8039, 340.8405,   0.8388,   0.0000],
        [332.9084,   0.0000, 487.6768, 181.2473,   0.8277,   0.0000]], device='cuda:0')
cls: tensor([0., 0.], device='cuda:0')
conf: tensor([0.8388, 0.8277], device='cuda:0')
data: tensor([[ 31.0373,  44.5269, 220.8039, 340.8405,   0.8388,   0.0000],
        [332.9084,   0.0000, 487.6768, 181.2473,   0.8277,   0.0000]], device='cuda:0')
id: None
is_track: False
orig_shape: (640, 640)
shape: torch.Size([2, 6])
xywh: tensor([[125.9206, 192.6837, 189.7666, 296.3136],
        [410.2926,  90.6237, 154.7684, 181.2473]], device='cuda:0')
xywhn: tensor([[0.1968, 0.3011, 0.2965, 0.4630],
        [0.6411, 0.1416, 0.2418, 0.2832]], device='cuda:0')
xyxy: tensor([[ 31.0373,  44.5269, 220.8039, 340.8405],
        [332.9084,   0.0000, 487.6768, 181.2473]], device='cuda:0')
xyxyn: tensor([[0.0485, 0.0696, 0.3450, 0.5326],
        [0.5202, 0.0000, 0.7620, 0.2832]], dev

In [10]:
boxes.xyxy

tensor([[ 31.0373,  44.5269, 220.8039, 340.8405],
        [332.9084,   0.0000, 487.6768, 181.2473]], device='cuda:0')

In [11]:
boxes.cls

tensor([0., 0.], device='cuda:0')

In [12]:
boxes.conf

tensor([0.8388, 0.8277], device='cuda:0')

In [19]:
boxes.orig_shape

(640, 640)

In [13]:
import torch

# Sample data (replace these tensors with your actual data)
confidences = torch.tensor([0.6, 0.4, 0.7, 0.8, 0.5])  # n x 1 tensor
bounding_boxes = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])  # n x 4 tensor

# Filter boxes based on confidence threshold (e.g., 0.5)
confidence_threshold = 0.5
filtered_indices = (confidences > confidence_threshold).nonzero().squeeze()

# Use the filtered indices to select bounding boxes
filtered_boxes = bounding_boxes[filtered_indices]

# Print the filtered boxes
print(filtered_boxes)


tensor([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])


In [17]:
import torch

# Sample data (replace these tensors with your actual data)
confidences = torch.tensor([0.6, 0.4, 0.7, 0.8, 0.5])  # n x 1 tensor
bounding_boxes = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])  # n x 4 tensor

# Define a confidence threshold (e.g., 0.5)
confidence_threshold = 0.5

# Filter boxes based on confidence threshold
filtered_boxes = bounding_boxes[confidences > confidence_threshold]

# Print the filtered boxes
print(filtered_boxes)


tensor([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])


In [16]:
(confidences > confidence_threshold).nonzero().squeeze()

tensor([0, 2, 3])

In [18]:
box = boxes[0]
box

WARNING  'Boxes.boxes' is deprecated. Use 'Boxes.data' instead.


ultralytics.engine.results.Boxes object with attributes:

boxes: tensor([[1.5846e+02, 6.1584e-02, 3.2676e+02, 2.2193e+02, 8.2209e-01, 0.0000e+00]], device='cuda:0')
cls: tensor([0.], device='cuda:0')
conf: tensor([0.8221], device='cuda:0')
data: tensor([[1.5846e+02, 6.1584e-02, 3.2676e+02, 2.2193e+02, 8.2209e-01, 0.0000e+00]], device='cuda:0')
id: None
is_track: False
orig_shape: (640, 640)
shape: torch.Size([1, 6])
xywh: tensor([[242.6108, 110.9946, 168.2961, 221.8661]], device='cuda:0')
xywhn: tensor([[0.3791, 0.1734, 0.2630, 0.3467]], device='cuda:0')
xyxy: tensor([[1.5846e+02, 6.1584e-02, 3.2676e+02, 2.2193e+02]], device='cuda:0')
xyxyn: tensor([[2.4760e-01, 9.6226e-05, 5.1056e-01, 3.4676e-01]], device='cuda:0')

In [9]:
box.xyxy[0]

NameError: name 'box' is not defined

In [9]:
box_lst = []
for box in boxes:
    box_lst.append(box)

In [10]:
box_lst

WARNING  'Boxes.boxes' is deprecated. Use 'Boxes.data' instead.


[ultralytics.engine.results.Boxes object with attributes:
 
 boxes: tensor([[1.5846e+02, 6.1584e-02, 3.2676e+02, 2.2193e+02, 8.2209e-01, 0.0000e+00]], device='cuda:0')
 cls: tensor([0.], device='cuda:0')
 conf: tensor([0.8221], device='cuda:0')
 data: tensor([[1.5846e+02, 6.1584e-02, 3.2676e+02, 2.2193e+02, 8.2209e-01, 0.0000e+00]], device='cuda:0')
 id: None
 is_track: False
 orig_shape: (640, 640)
 shape: torch.Size([1, 6])
 xywh: tensor([[242.6108, 110.9946, 168.2961, 221.8661]], device='cuda:0')
 xywhn: tensor([[0.3791, 0.1734, 0.2630, 0.3467]], device='cuda:0')
 xyxy: tensor([[1.5846e+02, 6.1584e-02, 3.2676e+02, 2.2193e+02]], device='cuda:0')
 xyxyn: tensor([[2.4760e-01, 9.6226e-05, 5.1056e-01, 3.4676e-01]], device='cuda:0')]

In [6]:
store = zip([1,2,3], [4,5,6])

In [7]:
for elem in store:
    print(elem)

(1, 4)
(2, 5)
(3, 6)


In [13]:
str(datetime.now().date())

'2023-10-21'

In [40]:
arr = range(20000000)

In [41]:
start = time.time()
for elem in arr:
    a = 1
end = time.time()
print(round(end-start, 2))

0.7


In [42]:
start = time.time()
for i in arr:
    elem = arr[i]
    a = 1
end = time.time()
print(round(end-start, 2))

2.43
